spring:
  application:
    name: springcloud-provider
  boot:
    admin:
      client:
        url: http://localhost:9999
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always